# Auto-sync hook: commits + pushes meaningful changes.
# Called by Claude Code Stop hook after each response.
# Cross-platform path detection — works on any machine regardless of username.

$ErrorActionPreference = "Continue"
$ProjectRoot = Split-Path -Parent $PSScriptRoot
Set-Location $ProjectRoot

function Find-MasterRoot {
    $candidate = Split-Path -Parent $ProjectRoot
    if ((Test-Path "$candidate\CLAUDE.md") -or (Test-Path "$candidate/CLAUDE.md")) { return $candidate }
    if ($env:CLAUDE_MASTER_ROOT -and (Test-Path $env:CLAUDE_MASTER_ROOT)) { return $env:CLAUDE_MASTER_ROOT }
    return $null
}
$MasterRoot = Find-MasterRoot

# --- phone-card alerts (2026-10-08) ---
# Generated by the master scripts/cardify-subhooks.py; change it there, then rerun it.
# Phone card = bold Korean title, at most 4 plain lines, a to-do line, a #tag
# (master shared-lib/botkit/card.py). ASCII only: PS 5.1 misreads BOM-less UTF-8,
# so the Korean is \u-escaped and decoded by K. Raw git output never goes to the
# phone: it is printed here and kept in .git/auto-sync-alert-detail.txt.
# $env:AUTO_SYNC_ALERT_DRY = <file> writes the card there instead of sending it.
function K([string]$s) { return [regex]::Unescape($s) }
function ConvertTo-CardHtml([string]$s) { return $s.Replace('&', '&amp;').Replace('<', '&lt;').Replace('>', '&gt;') }

function Send-Card {
    param([string]$Title, [string[]]$Lines, [string]$Todo, [string]$Next, [string]$Tag, [string]$Detail)
    $body = @($Lines | Where-Object { $_ })
    $tail = @((K '\ud560 \uc77c: ') + $(if ($Todo) { $Todo } else { K '\uc5c6\uc74c' }))
    if ($Next) { $tail += (K '\ub2e4\uc74c: ') + $Next }
    $tagLine = '#' + ($Tag -replace '[^0-9A-Za-z\uac00-\ud7a3_]', '_')
    $plain = (@($Title) + $body + @('') + $tail + @($tagLine)) -join "`n"
    $html = (@('<b>' + (ConvertTo-CardHtml $Title) + '</b>') + @($body | ForEach-Object { ConvertTo-CardHtml $_ }) +
             @('') + @($tail | ForEach-Object { ConvertTo-CardHtml $_ }) + @($tagLine)) -join "`n"
    Write-Host $plain -ForegroundColor Red
    if ($Detail) {
        Write-Host $Detail
        try { [IO.File]::WriteAllText((Join-Path $ProjectRoot '.git/auto-sync-alert-detail.txt'), $Detail, (New-Object Text.UTF8Encoding $false)) } catch {}
    }
    if ($env:AUTO_SYNC_ALERT_DRY) {
        [IO.File]::WriteAllText($env:AUTO_SYNC_ALERT_DRY, $html, (New-Object Text.UTF8Encoding $false))
        return
    }
    $alertFile = $null
    if (Test-Path '.alert.env') { $alertFile = '.alert.env' }
    elseif ($MasterRoot -and (Test-Path (Join-Path $MasterRoot '.alert.env'))) { $alertFile = Join-Path $MasterRoot '.alert.env' }
    elseif (Test-Path (Join-Path $HOME '.alert.env')) { $alertFile = Join-Path $HOME '.alert.env' }
    if (-not $alertFile) { return }
    $envText = [IO.File]::ReadAllText((Resolve-Path $alertFile).Path)
    $tok = if ($envText -match '(?m)^\s*BOT_TOKEN\s*=\s*(.+)$') { $matches[1].Trim().Trim('"').Trim("'") } else { $null }
    $cid = if ($envText -match '(?m)^\s*USER_DIRECT_CHAT_ID\s*=\s*(.+)$') { $matches[1].Trim().Trim('"').Trim("'") }
           elseif ($envText -match '(?m)^\s*CHAT_ID\s*=\s*(.+)$') { $matches[1].Trim().Trim('"').Trim("'") } else { $null }
    if (-not ($tok -and $cid)) { return }
    try { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12 } catch {}
    # HTML first; if Telegram refuses it, the same words as plain text (formatting never costs the alert)
    foreach ($p in @(@{chat_id = $cid; text = $html; parse_mode = 'HTML'}, @{chat_id = $cid; text = $plain})) {
        try {
            $bytes = [Text.Encoding]::UTF8.GetBytes(($p | ConvertTo-Json -Compress))
            $r = Invoke-RestMethod -Uri "https://api.telegram.org/bot$tok/sendMessage" -Method Post -Body $bytes `
                 -ContentType 'application/json; charset=utf-8' -TimeoutSec 10
            if ($r.ok) { $script:CardSent = $p.Keys -contains 'parse_mode'; return }
        } catch {}
    }
}

function Send-SuspectCard([string]$Proj, [string[]]$Files) {
    Send-Card -Title ((K '\ud83d\udd34 {0} \uc790\ub3d9 \ubc31\uc5c5 \uba48\ucda4: \ube44\ubc00\ud0a4 \uc758\uc2ec \ud30c\uc77c, \ud074\ub85c\ub4dc \ud655\uc778 \ud544\uc694') -f $Proj) -Lines @(
        ((K '\uc62c\ub9b4 \ubcc0\uacbd \uc911\uc5d0 \ube44\ubc00\ud0a4\ucc98\ub7fc \ubcf4\uc774\ub294 \ud30c\uc77c\uc774 {0}\uac1c \uc788\uc5b4 \uc544\ubb34\uac83\ub3c4 \uc62c\ub9ac\uc9c0 \uc54a\uc558\uc2b5\ub2c8\ub2e4.') -f @($Files).Count),
        (K '\uadf8 \ud30c\uc77c\uc744 \uce58\uc6b0\uae30 \uc804\uae4c\uc9c0 \uc774 \ud3f4\ub354\uc758 \uc790\ub3d9 \ubc31\uc5c5\uc740 \ub9e4\ubc88 \uba48\ucda5\ub2c8\ub2e4.')
    ) -Todo (K '\ud074\ub85c\ub4dc\uc5d0\uac8c "\uc790\ub3d9 \ubc31\uc5c5 \uba48\ucd98 \ud30c\uc77c \ud655\uc778\ud574\uc918" \ub77c\uace0 \ub9d0\ud558\uae30') -Tag (K '\uc790\ub3d9\ubc31\uc5c5') `
      -Detail ("suspect files:`n" + (@($Files) -join "`n"))
}

# git push output -> (one plain reason, what the owner does about it, the action for the title)
function Get-PushFailReason([string]$Out) {
    if ($Out -match 'GH013|push declined|cannot contain secrets|protected branch|pre-receive hook declined') {
        return @((K '\uae43\ud5c8\ube0c\uac00 \ube44\ubc00\uac12 \uc758\uc2ec\uc774\ub098 \ubcf4\ud638 \uaddc\uce59 \ub54c\ubb38\uc5d0 \ubc1b\uc9c0 \uc54a\uc558\uc2b5\ub2c8\ub2e4.'), (K '\ud074\ub85c\ub4dc\uc5d0\uac8c "\ud478\uc2dc \uac70\uc808 \uc774\uc720 \ud655\uc778\ud574\uc918" \ub77c\uace0 \ub9d0\ud558\uae30'), (K '\ud074\ub85c\ub4dc \ud655\uc778 \ud544\uc694')) }
    if ($Out -match 'rejected|non-fast-forward|fetch first') {
        return @((K '\ub2e4\ub978 \uae30\uae30\ub098 \uc138\uc158\uc774 \uba3c\uc800 \uc62c\ub9b0 \uae30\ub85d\uc774 \uc788\uc5b4 \uae43\ud5c8\ube0c\uac00 \uac70\uc808\ud588\uc2b5\ub2c8\ub2e4.'), (K '\ud074\ub85c\ub4dc\uc5d0\uac8c "\uc790\ub3d9 \ubc31\uc5c5 \uc2e4\ud328 \uace0\uccd0\uc918" \ub77c\uace0 \ub9d0\ud558\uae30'), (K '\ud074\ub85c\ub4dc\uc5d0\uac8c \ub9e1\uae30\uae30')) }
    if ($Out -match 'Authentication failed|Permission denied|could not read Username|Repository not found|\b403\b') {
        return @((K '\uae43\ud5c8\ube0c \ub85c\uadf8\uc778\uc774 \ud480\ub838\uac70\ub098 \uc774 \uc800\uc7a5\uc18c\uc5d0 \uc62c\ub9b4 \uad8c\ud55c\uc774 \uc5c6\uc2b5\ub2c8\ub2e4.'), (K '\ud074\ub85c\ub4dc\uc5d0\uac8c "\uae43\ud5c8\ube0c \ub85c\uadf8\uc778 \ud655\uc778\ud574\uc918" \ub77c\uace0 \ub9d0\ud558\uae30'), (K '\ub85c\uadf8\uc778 \ud655\uc778 \ud544\uc694')) }
    # before the network check: git adds "Could not read from remote repository" to this one too
    if ($Out -match 'no upstream|No configured push destination|does not match any|does not appear to be a git repository') {
        return @((K '\uc62c\ub824 \ubcf4\ub0bc \uae43\ud5c8\ube0c \uc800\uc7a5\uc18c\uac00 \uc5f0\uacb0\ub3fc \uc788\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.'), (K '\ud074\ub85c\ub4dc\uc5d0\uac8c "\uae43\ud5c8\ube0c \uc800\uc7a5\uc18c \uc5f0\uacb0\ud574\uc918" \ub77c\uace0 \ub9d0\ud558\uae30'), (K '\ud074\ub85c\ub4dc\uc5d0\uac8c \ub9e1\uae30\uae30')) }
    if ($Out -match 'Could not resolve host|unable to access|timed out|Connection (reset|refused)|Failed to connect|Could not read from remote') {
        return @((K '\uc778\ud130\ub137\uc774\ub098 \uae43\ud5c8\ube0c \uc5f0\uacb0\uc774 \uc548 \ub410\uc2b5\ub2c8\ub2e4.'), (K '\uc5c6\uc74c (\uac19\uc740 \uc54c\ub9bc\uc774 \uacc4\uc18d \uc624\uba74 \uc778\ud130\ub137 \ud655\uc778)'), (K '\ud560 \uc77c \uc5c6\uc74c, \ub2e4\uc2dc \uc2dc\ub3c4\ud568')) }
    return @((K '\uae43\ud5c8\ube0c\uac00 \ubc1b\uc9c0 \uc54a\uc558\uace0, \uc774\uc720\ub294 \uc790\ub3d9\uc73c\ub85c \uac00\ub9ac\uc9c0 \ubabb\ud588\uc2b5\ub2c8\ub2e4.'), (K '\ud074\ub85c\ub4dc\uc5d0\uac8c "\uc790\ub3d9 \ubc31\uc5c5 \uc2e4\ud328 \uc774\uc720 \ubd10\uc918" \ub77c\uace0 \ub9d0\ud558\uae30'), (K '\ud074\ub85c\ub4dc \ud655\uc778 \ud544\uc694'))
}

function Send-PushFailCard([string]$Proj, [string]$Output) {
    $why = Get-PushFailReason $Output
    Send-Card -Title ((K '\ud83d\udd34 {0} \uae43\ud5c8\ube0c \uc62c\ub9ac\uae30 \uc2e4\ud328: {1}') -f $Proj, $why[2]) -Lines @(
        $why[0],
        (K '\ubc14\ub010 \ub0b4\uc6a9\uc740 \uc774 \ucef4\ud4e8\ud130\uc5d0 \uc800\uc7a5\ud574 \ub450\uc5c8\uace0, \uae43\ud5c8\ube0c\ub85c \uc62c\ub9ac\ub294 \uac83\ub9cc \uc2e4\ud328\ud588\uc2b5\ub2c8\ub2e4.')
    ) -Todo $why[1] -Next (K '\ub300\ud654\uac00 \ub05d\ub0a0 \ub54c\ub9c8\ub2e4 \ub2e4\uc2dc \uc62c\ub824 \ubd05\ub2c8\ub2e4.') -Tag (K '\uc790\ub3d9\ubc31\uc5c5') `
      -Detail ("git push:`n" + $Output)
}
# --- end phone-card alerts (2026-10-08) ---

# 0. Git repo?
if (-not (Test-Path ".git")) { exit 0 }

# 0. Multi-agent safety (2026-07-09): 다른 에이전트/세션이 git 작업 중이면 이번 턴 스킵.
#    index.lock / mid-merge / rebase / cherry-pick → 다음 턴 자동 재시도 (마스터 훅과 대칭).
if ((Test-Path ".git/index.lock") -or (Test-Path ".git/MERGE_HEAD") -or
    (Test-Path ".git/rebase-merge") -or (Test-Path ".git/rebase-apply") -or
    (Test-Path ".git/CHERRY_PICK_HEAD")) { exit 0 }

# 1. Any changes?
$changes = git status --porcelain 2>$null
if ([string]::IsNullOrWhiteSpace("$changes")) { exit 0 }

# 2. Hard block on suspect files
$suspect = $changes | Where-Object { $_ -match '\.env$|\.alert\.env|wallet\.json|\.key$|\.pem$|id_rsa|mnemonic|\.exe$' -and $_ -notmatch '\.example$' }
if ($suspect) {
    Send-SuspectCard -Proj (Split-Path $ProjectRoot -Leaf) -Files @($suspect)
    exit 1
}

# 3. Stage specific patterns (no `git add .`)
foreach ($pattern in @('CLAUDE.md', 'PROGRESS.md', 'DEFERRED.md', 'CHANGELOG.md', 'MEMORY.md', '.gitignore', 'README.md', '*.py', '*.ts', '*.tsx', '*.js', '*.rs', '*.toml', '*.yaml', '*.yml', '*.md')) {
    git add $pattern 2>$null
}
foreach ($dir in @('scripts', 'src', 'tests', 'docs', 'app', 'static', 'public', 'lib', 'feeds', 'detectors', 'wallet')) {
    if (Test-Path $dir) { git add $dir 2>$null }
}

# 4. Anything staged?
$staged = git diff --cached --name-only 2>$null
if ([string]::IsNullOrWhiteSpace("$staged")) { exit 0 }

# 5. Commit
$ts = Get-Date -Format "MM-dd HH:mm"
$proj = Split-Path $ProjectRoot -Leaf
git commit -qm "auto-sync ${proj} ${ts}" 2>$null
if ($LASTEXITCODE -ne 0) { exit 0 }

# 6. Push (upstream 있는 repo만 — 로컬 전용 repo는 조용히 스킵)
git rev-parse --abbrev-ref --symbolic-full-name "@{u}" 2>$null | Out-Null
if ($LASTEXITCODE -eq 0) {
    $push = git push 2>&1
    if ($LASTEXITCODE -ne 0) {
        Send-PushFailCard -Proj $proj -Output ($push -join "`n")
        exit 1
    }
}

# 7. Success: stamp .last-sync
Get-Date -Format "yyyy-MM-ddTHH:mm:ssK" | Out-File -FilePath ".last-sync" -Encoding UTF8 -NoNewline
exit 0